---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: company-ingress
  labels:
    app: company-ingress
    chart: {{ template "company.chart" . }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: /api/company
            backend:
              serviceName: company
              servicePort: 80
          - path: /api/person
            backend:
              serviceName: person
              servicePort: 80