---
apiVersion: v1
kind: Service
metadata:
  name: person
  labels:
    app: person
    chart: {{ template "company.chart" . }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3008
      name: http
  selector:
    app: person
    release: {{ $.Release.Name }}