---
apiVersion: v1
kind: Service
metadata:
  name: company
  labels:
    app: company
    chart: {{ template "company.chart" . }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: company
    release: {{ $.Release.Name }}