---
apiVersion: v1
kind: Service
metadata:
  name: company-db
  labels:
    app: company-db
    chart: {{ template "company.chart" . }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      name: postgresql
  selector:
    app: company-db
    release: {{ $.Release.Name }}